# Generated by Django 5.1.3 on 2024-11-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
