# Generated by Django 5.1.3 on 2024-11-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
